export const pathes = {
	catalog: 'catalog',
	profile: '/lk/profile',
	managment: '/lk/management',
	organizations: '/lk/organizations',
	employees: '/lk/employees',
	settlements: '/lk/settlements',
	orders: '/lk/orders',
	favorites: '/lk/favorites',
	refunds: '/lk/refunds',
	documents: '/lk/documents',
	offers: '/lk/offers',
	bonus: '/lk/bonus',
	messages: '/lk/messages',
	help: '/lk/help',
};
