import { ICatalogMenuData } from './CatalogMenu.types';

export const CatalogMenuData: ICatalogMenuData = {
	baner: {
		heading: 'Дачный сезон',
		text: 'Новый ассортимент товаров для сада и дачи',
		image: '/images/baner/wheelbarrow.png',
	},
	categories: [
		{
			id: '0',
			value: 'Автотовары',
			link: '/catalog-first',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-third',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-third',
							subcategories: null,
						},
					],
				},
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-third',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-third',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-third',
							subcategories: null,
						},
					],
				},
			],
		},
		{
			id: '1',
			value: 'Инструмент',
			link: '',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
				{
					id: '1',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
			],
		},
		{
			id: '2',
			value: 'Косметика и уход',
			link: '',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
				{
					id: '1',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
			],
		},
		{
			id: '3',
			value: 'Электрика и вентиляция',
			link: '',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
				{
					id: '1',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
			],
		},
		{
			id: '4',
			value: 'Дом и дача',
			link: '',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
				{
					id: '1',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
			],
		},
		{
			id: '5',
			value: 'Крепеж и фурнитура',
			link: '',
			subcategories: [
				{
					id: '0',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
				{
					id: '1',
					value: 'Автохимия и автокосметика',
					link: '/catalog-second',
					subcategories: [
						{
							id: '0',
							value: 'Мовиль',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '1',
							value: 'Преобразователь ржавчины',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '2',
							value: 'Смазки автомобильные',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '3',
							value: 'Уход за двигателем',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '4',
							value: 'Уход за кузовом',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '5',
							value: 'Уход за салоном',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '6',
							value: 'Уход за стеклами и зеркалами',
							link: '/catalog-second',
							subcategories: null,
						},
						{
							id: '7',
							value: 'Уход за шинами и дисками',
							link: '/catalog-second',
							subcategories: null,
						},
					],
				},
			],
		},
	],
};
